language: haskell

env:
  global: 
    secure: "PGhJXCunvZyeupgAGlMPNXG1BDbRpLCPVQXP29EnooGiaVN1LTj4FJfhvuX0\nGbVFxYDw7dGgI90XetnVXVZgMtnEHpq2arepjuGdKcCaDAgMsirrx4Yz7exR\n40LwKCiexZ0YY+GIREIKJqgK3onvh6YAGcQT28RQctEn9tXTQhM="

install:  sh ./builddep.sh 

