language: haskell
env:
  global:
    secure: "W+MVU/iajtXr5/a3WeRE0IDgLBWBTipq34t/Z/eHybKjoPV7TDpaBXCSLdvm\nEafv/Xb2UX23guPwW9HRM0V2b8XEx/YoNzUfJk2Fy5Qq6p9I0A4G5lpEaTpF\nbgfdMJQj6nwIPFyk8KihxurD6+ELT6g2l7MPIblhi0l+DmzGJL0="

install:  sh ./builddep.sh 
