language: haskell
env:
  global:
    secure: "QCs0bXunP5BgclczpwcQ0/HQPOZQGs+6N4IiJQjPKTJauspPcBsPhVT7OFI8\nX1qy4scXwwSa69KIQqNOzRfHEPDDl9L6I3f2IL3b7jtr2plmEiCpgQSGfGAX\nAqUk4hTqKOQ7ZaN3z8kD+9ZZt5iRIPUIk/4wPoMOE1vhtETfcDQ="

install:  sh ./builddep.sh 
